#!/usr/bin/env python3
"""
rebrand-hyperxtalk.py
Replaces LiveCode / com.runrev branding with HyperXTalk / com.hyperxtalk
across all source plist, gyp, gypi, and related config files.

Run from the repo root:
    python3 prebuilt/scripts/rebrand-hyperxtalk.py
"""

import os
import re
import sys

REPO = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

# ── Ordered replacements (most-specific first to avoid double-substitution) ──
REPLACEMENTS = [
    # --- Bundle ID strings ---
    ("com.runrev.livecode.installer",   "com.hyperxtalk.hyperxtalk.installer"),
    ("com.runrev.livecode.test",        "com.hyperxtalk.hyperxtalk.test"),
    ("com.runrev.livecode.objects-1",   "com.hyperxtalk.hyperxtalk.objects-1"),
    ("com.runrev.livecode.stack",       "com.hyperxtalk.hyperxtalk.stack"),
    ("com.runrev.livecode",             "com.hyperxtalk.hyperxtalk"),
    ("com.runrev.revolution.stack",     "com.hyperxtalk.standalone.stack"),
    ("com.runrev.revolution",           "com.hyperxtalk.standalone"),
    ("com.runrev.PushNotificationApp",  "com.hyperxtalk.PushNotificationApp"),
    ("com.runrev.reviphone",            "com.hyperxtalk.reviphone"),
    ("com.runrev.revandroid",           "com.hyperxtalk.revandroid"),
    ("com.runrev.revbrowser",           "com.hyperxtalk.revbrowser"),
    ("com.runrev.revdb",                "com.hyperxtalk.revdb"),
    ("com.runrev.dbsqlite",             "com.hyperxtalk.dbsqlite"),
    ("com.runrev.dbmysql",              "com.hyperxtalk.dbmysql"),
    ("com.runrev.dbodbc",               "com.hyperxtalk.dbodbc"),
    ("com.runrev.dbpostgresql",         "com.hyperxtalk.dbpostgresql"),
    ("com.runrev.revxml",               "com.hyperxtalk.revxml"),
    ("com.runrev.revzip",               "com.hyperxtalk.revzip"),
    ("com.runrev.revspeech",            "com.hyperxtalk.revspeech"),
    ("com.runrev.revpdfprinter",        "com.hyperxtalk.revpdfprinter"),
    ("com.runrev.webme",                "com.hyperxtalk.webme"),
    # catch-all for any remaining com.runrev.*
    ("com.runrev.",                     "com.hyperxtalk."),

    # --- Objective-C class name in plists (NSPrincipalClass) ---
    # NOTE: the C++ class itself in mac-core.mm must be renamed separately.
    ("com_runrev_livecode_MCApplication", "com_hyperxtalk_hyperxtalk_MCApplication"),

    # --- Display / bundle name strings ---
    ("LiveCode-Community",  "HyperXTalk"),
    ("Standalone-Community","HyperXTalk-Standalone"),
    # CFBundleName values
    ("livecodeinstaller",   "hyperxtalkcommunity"),
    # Human-readable product name
    ("LiveCode",            "HyperXTalk"),
    # runrev company references that may remain
    ("RunRev",              "HyperXTalk"),
    ("runrev",              "hyperxtalk"),
]

# ── Files / directories to process ──
# Source plist templates and gyp/gypi files; skip mac-bin (regenerated by build)
SOURCE_GLOBS = [
    "engine/rsrc/*.plist",
    "engine/Test-Info.plist",
    "engine/engine.gyp",
    "engine/kernel.gyp",
    "engine/app-bundle-template.gypi",
    "engine/engine-sources.gypi",
    "livecode.gyp",
    "common.gypi",
    "builder/mac_info.plist",
    "revbrowser/rsrc/*.plist",
    "revdb/rsrc/*.plist",
    "revmobile/*.plist",
    "revxml/rsrc/*.plist",
    "revzip/rsrc/*.plist",
    "revspeech/rsrc/*.plist",
    "revpdfprinter/rsrc/*.plist",
    "lcidlc/lcidlc.gyp",
    "extensions/extensions.gyp",
]

def collect_files():
    import glob
    files = []
    for pattern in SOURCE_GLOBS:
        full = os.path.join(REPO, pattern)
        matches = glob.glob(full)
        files.extend(matches)
    return sorted(set(files))

def process_file(path):
    with open(path, "r", encoding="utf-8", errors="replace") as f:
        original = f.read()

    text = original
    for old, new in REPLACEMENTS:
        text = text.replace(old, new)

    if text != original:
        with open(path, "w", encoding="utf-8") as f:
            f.write(text)
        return True
    return False

def main():
    files = collect_files()
    changed = []
    skipped = []

    for path in files:
        if not os.path.isfile(path):
            continue
        rel = os.path.relpath(path, REPO)
        if process_file(path):
            changed.append(rel)
            print(f"  UPDATED  {rel}")
        else:
            skipped.append(rel)

    print()
    print(f"Done. {len(changed)} file(s) updated, {len(skipped)} unchanged.")

    print()
    print("═══ Manual steps still required ═══")
    print()
    print("1. Rename the main app binary / product name in Xcode project:")
    print("   build-mac/livecode/engine/engine.xcodeproj/project.pbxproj")
    print("   Search: LiveCode-Community  →  Replace: HyperXTalk")
    print()
    print("2. Rename the Objective-C class in source code:")
    print("   engine/src/mac-core.mm (and any other file that defines/registers")
    print("   'com_runrev_livecode_MCApplication').")
    print("   The plist NSPrincipalClass key was updated to")
    print("   'com_hyperxtalk_hyperxtalk_MCApplication'; the C++ class name")
    print("   must match exactly.")
    print()
    print("3. After editing source, rebuild:")
    print("   make compile-mac")
    print()
    print("4. Re-sign all binaries after rebuild:")
    print("   find mac-bin -not -name '*.dSYM' -type f | while read F; do")
    print("     file \"$F\" | grep -qE 'Mach-O|bundle' && codesign --force --sign - \"$F\"")
    print("   done")
    print("   find mac-bin -name '*.app' -exec codesign --force --deep --sign - {} \\;")

if __name__ == "__main__":
    main()
